services:

  db:
    image: mongo:latest
    container_name: mongodb
    command: mongod --port 27017 --replSet rs0 --bind_ip_all --keyFile /data/configdb/keyfile
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_REPLICA_SET_KEY: ${MONGO_REPLICA_SET_KEY}
    ports:
      - ${DB_PORT}:27017
    healthcheck:
      test: 'mongosh --quiet --port 27017 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'
      interval: 5s
    volumes:
      - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
      - db_data:/data
      - db_data_config:/data/configdb

  db_init:
    image: mongo:latest
    restart: no
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        mongosh -u $DB_USER -p $DB_PASS --host db --port 27017 --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"localhost:27017\" }
            ]
          })
        '
      "

volumes:
  db_data:
  db_data_config:
